version: '3.8'
services:
  mssql-tests:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AStrong!Passw0rd
    volumes:
      - mssql_data-tests:/var/opt/mssql

  skiservice-tests:
    image: fokklz/skiservice-api
    volumes:
      - ./Logs:/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-tests;Database=JetStream;User ID=SA;Password=AStrong!Passw0rd;TrustServerCertificate=True;
      - CORS__AllowedOrigins=http://127.0.0.1:3000,http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500
    ports:
      - "9000:8080"
    depends_on:
      - mssql-tests

volumes:
  mssql_data-tests: {}
