//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveUp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveUp.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy me a coffee ähnelt.
        /// </summary>
        internal static string About_Button_Donate {
            get {
                return ResourceManager.GetString("About.Button.Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string About_Button_Settings {
            get {
                return ResourceManager.GetString("About.Button.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developers ähnelt.
        /// </summary>
        internal static string About_Devs_Title {
            get {
                return ResourceManager.GetString("About.Devs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SaveUp ähnelt.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string Add_Submit {
            get {
                return ResourceManager.GetString("Add.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add a Product ähnelt.
        /// </summary>
        internal static string Add_Title {
            get {
                return ResourceManager.GetString("Add.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imprint ähnelt.
        /// </summary>
        internal static string App_Imprint {
            get {
                return ResourceManager.GetString("App.Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Policy ähnelt.
        /// </summary>
        internal static string App_PrivacyPolicy {
            get {
                return ResourceManager.GetString("App.PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timespan ähnelt.
        /// </summary>
        internal static string App_Time {
            get {
                return ResourceManager.GetString("App.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day ähnelt.
        /// </summary>
        internal static string App_Time_Day {
            get {
                return ResourceManager.GetString("App.Time.Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        internal static string App_Time_Days {
            get {
                return ResourceManager.GetString("App.Time.Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour ähnelt.
        /// </summary>
        internal static string App_Time_Hour {
            get {
                return ResourceManager.GetString("App.Time.Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        internal static string App_Time_Hours {
            get {
                return ResourceManager.GetString("App.Time.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute ähnelt.
        /// </summary>
        internal static string App_Time_Minute {
            get {
                return ResourceManager.GetString("App.Time.Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        internal static string App_Time_Minutes {
            get {
                return ResourceManager.GetString("App.Time.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second ähnelt.
        /// </summary>
        internal static string App_Time_Second {
            get {
                return ResourceManager.GetString("App.Time.Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string App_Time_Seconds {
            get {
                return ResourceManager.GetString("App.Time.Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SaveUp ähnelt.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot your password? ähnelt.
        /// </summary>
        internal static string AppLogin_Login_ForgotPassword {
            get {
                return ResourceManager.GetString("AppLogin.Login.ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No account? Register now ähnelt.
        /// </summary>
        internal static string AppLogin_Login_Register {
            get {
                return ResourceManager.GetString("AppLogin.Login.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string AppLogin_Login_Submit {
            get {
                return ResourceManager.GetString("AppLogin.Login.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string AppLogin_Login_Title {
            get {
                return ResourceManager.GetString("AppLogin.Login.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send reset code ähnelt.
        /// </summary>
        internal static string AppLogin_PasswordReset_CodeButton {
            get {
                return ResourceManager.GetString("AppLogin.PasswordReset.CodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your email address to receive a reset code. ähnelt.
        /// </summary>
        internal static string AppLogin_PasswordReset_Info {
            get {
                return ResourceManager.GetString("AppLogin.PasswordReset.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to Login ähnelt.
        /// </summary>
        internal static string AppLogin_PasswordReset_Login {
            get {
                return ResourceManager.GetString("AppLogin.PasswordReset.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password reset ähnelt.
        /// </summary>
        internal static string AppLogin_PasswordReset_Title {
            get {
                return ResourceManager.GetString("AppLogin.PasswordReset.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die By registering you accept our Terms of Service. ähnelt.
        /// </summary>
        internal static string AppLogin_Register_Disclaimer {
            get {
                return ResourceManager.GetString("AppLogin.Register.Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to Login ähnelt.
        /// </summary>
        internal static string AppLogin_Register_Login {
            get {
                return ResourceManager.GetString("AppLogin.Register.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        internal static string AppLogin_Register_Submit {
            get {
                return ResourceManager.GetString("AppLogin.Register.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        internal static string AppLogin_Register_Title {
            get {
                return ResourceManager.GetString("AppLogin.Register.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item added successfully ähnelt.
        /// </summary>
        internal static string Dialog_CreatedItem_Message {
            get {
                return ResourceManager.GetString("Dialog.CreatedItem.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success ähnelt.
        /// </summary>
        internal static string Dialog_CreatedItem_Title {
            get {
                return ResourceManager.GetString("Dialog.CreatedItem.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        internal static string Dialog_Ok {
            get {
                return ResourceManager.GetString("Dialog.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string Form_Clear {
            get {
                return ResourceManager.GetString("Form.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        internal static string Form_ConfirmPassword {
            get {
                return ResourceManager.GetString("Form.ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Form_Description {
            get {
                return ResourceManager.GetString("Form.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        internal static string Form_Email {
            get {
                return ResourceManager.GetString("Form.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Form_Password {
            get {
                return ResourceManager.GetString("Form.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        internal static string Form_Price {
            get {
                return ResourceManager.GetString("Form.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product name ähnelt.
        /// </summary>
        internal static string Form_Product {
            get {
                return ResourceManager.GetString("Form.Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string Form_Username {
            get {
                return ResourceManager.GetString("Form.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string Home_Details_Remove {
            get {
                return ResourceManager.GetString("Home.Details.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Out ähnelt.
        /// </summary>
        internal static string Settings_Button_Logout {
            get {
                return ResourceManager.GetString("Settings.Button.Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset timespan ähnelt.
        /// </summary>
        internal static string Settings_Button_Timespan {
            get {
                return ResourceManager.GetString("Settings.Button.Timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        internal static string Settings_Currency_Label {
            get {
                return ResourceManager.GetString("Settings.Currency.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Settings_Language_Label {
            get {
                return ResourceManager.GetString("Settings.Language.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        internal static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings.Theme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme ähnelt.
        /// </summary>
        internal static string Settings_Theme_Label {
            get {
                return ResourceManager.GetString("Settings.Theme.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        internal static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings.Theme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        internal static string Settings_Theme_System {
            get {
                return ResourceManager.GetString("Settings.Theme.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
    }
}
